<?php

namespace QW\FW\Search\ArraySearch;

class InterpolationSearch extends AbstractArraySearch
{
	public function __construct( array $data )
	{
		parent::__construct( $data ); // TODO: Change the autogenerated stub
	}

	public function search()
	{
		// TODO: Implement search() method.
	}
}