<?php

namespace QW\FW\Search\ArraySearch;

class PruneAndSearch extends AbstractArraySearch {
	public function __construct( array $data, $debug = FALSE ) {
		parent::__construct( $data, $debug ); // TODO: Change the autogenerated stub
	}

	public function search() {
		// TODO: Implement search() method.
	}
}