<?php
	/**
	 * Created by PhpStorm.
	 * User: Tomáš
	 * Date: 8. 6. 2016
	 * Time: 18:39
	 */

	namespace QW\FW\Utils\Math\Geom;

	use QW\FW\Basic\Object;

	/**
	 * Class Line
	 * @package QW\FW\Utils\Math\Geom
	 */
	class Line extends Object {

		private $pointA;
		private $pointB;


		/**
		 * Line constructor.
		 * @param Point $pointA
		 * @param Point $pointB
		 * @param $debug
		 */
		public function __construct ( Point $pointA, Point $pointB ) {
			parent::__construct ();

			$this->pointA = $pointA;
			$this->pointB = $pointB;
		}

		public function __destruct () {
			$this->pointA = NULL;
			$this->pointB = NULL;

			parent::__destruct (); // TODO: Change the autogenerated stub
		}

		/**
		 * @return Point
		 */
		public function getPointA () {
			return $this->pointA;
		}

		/**
		 * @return Point
		 */
		public function getPointB () {
			return $this->pointB;
		}
	}