<?php
/**
 * Created by PhpStorm.
 * User: Tomáš
 * Date: 12. 7. 2015
 * Time: 13:21
 */

namespace QW\FW\Search\StringSearch;


class NaiveStringSearch extends AbstractStringSearch {
	public function __construct( $string, $debug = FALSE ) {
		parent::__construct( $string, $debug ); // TODO: Change the autogenerated stub
	}

	public function search() {
		// TODO: Implement search() method.
	}
}