<?php

namespace QW\FW\DataWorking\Search\StringSearch;

class NaiveStringSearch extends AbstractStringSearch {
	public function __construct( $string, $debug = FALSE ) {
		parent::__construct( $string, $debug ); // TODO: Change the autogenerated stub
	}

	public function search() {
		// TODO: Implement search() method.
	}
}