<?php

namespace QW\FW\DataWorking\Search\ArraySearch;

class InterpolationSearch extends AbstractArraySearch {
	public function __construct( array $data, $debug = FALSE ) {
		parent::__construct( $data ); // TODO: Change the autogenerated stub
	}

	public function search() {
		// TODO: Implement search() method.
	}
}